### ISSUE TITLE
Entity-XML: property names unification

### ISSUE THREAD

**Issue by SuperTux88** [diaspora/diaspora_federation#29]
As we are making changes to the protocol anyway, we can also unify some property names in the XML. This makes the code cleaner in the future.
- "diaspora handle" is called "diaspora ID" in the frontend, and should also be unified in the code (currently it's a mix of both). Also the author of a message should always be `author`.
- Relayables have a `parent`
- Retractions have a `target`
## This results in the following changes:
- `account_deletion`:
  - `diaspora_handle` -> `author`
- `comment`:
  - `diaspora_handle` -> `author`
- `conversation`:
  - `diaspora_handle` -> `author`
  - `participant_handles` -> `participants`
- `like`:
  - `diaspora_handle` -> `author`
  - `target_type` -> `parent_type`
- `message`:
  - `diaspora_handle` -> `author`
- `participation`:
  - `diaspora_handle` -> `author`
  - `target_type` -> `parent_type`
- `person`:
  - `diaspora_handle` -> `author`
- `photo`:
  - `diaspora_handle` -> `author`
- `poll_participation`:
  - `diaspora_handle` -> `author`
- `profile`:
  - `diaspora_handle` -> `author`
- `request`:
  - `sender_handle` -> `author`
  - `recipient_handle` -> `recipient`
- `reshare`:
  - `root_diaspora_id` -> `root_author`
  - `diaspora_handle` -> `author`
- `retraction`:
  - `diaspora_handle` -> `author`
  - `post_guid` -> `target_guid`
  - `type` -> `target_type`
- `status_message`:
  - `diaspora_handle` -> `author`
  - `raw_message` -> `text`
### v0.1.0 (for diaspora 0.6.0.0)
- [x] allow to receive messages with old and new property names
- [x] send messages with old property names
### v0.2.0 (for diaspora 0.7.0.0)
- [x] allow to receive messages with old and new property names
- [x] send messages with new property names
### v0.3.0 (probably for diaspora 0.8.0.0)
- [ ] remove old unused name mappings from the code

**Comment by jaywink** [comment]
Won't this break federation with just about everything that will not update to the latest version withint 3-4 releases - meaning most likely maybe Friendica but almost certainly all of Hubzilla?

The timetable is too ambitious, backwards compatibility should not be broken before the next major release. I'd like this timetable to be submitted to a proposal instead of just deciding on the schedule within a few people.

**Comment by denschub** [comment]
A "minor release" in our terms means 6 weeks. From federation v0.1.0 to v0.3.0, there will be 7-8 diaspora releases, which means there will be a 48 week deprecation period which is almost a year. We're (well, @SuperTux88 is) in close contact with a Friendica developer who will happily adjust their implementation. Mike is doing nothing but ranting around how bad everything is and how stupid we are, so there is no chance of working with him.

If people don't update their server within even the initial 24-week period between adding support and swapping the defaults, well, that's too bad. We've discussed that in the past on Loomio, there is no reason to do that again. And honestly, decisions about when to remove deprecate stuff should be done when there is actually stuff to be removed, not if there is only a vague time plan, since discussion about when we **eventually could** remove stuff is pointless.

**Comment by Flaburgan** [comment]
+1 with Dennis, I just feel a little bit weird about breaking stuff in a minor release. But we will see at this time, maybe we will be ready for 0.7 who knows :)

**Comment by jaywink** [comment]
> After four years, somebody is trying to fix the broken stuff

That makes it ok to smash everything to pieces in a minor release (following semver??) or not follow our proposal-led way of working (in this case regarding deprecation schedules, not actual what should be done).

It's not many days since you charged at me in private yelling "we have loomio for this stuff". But I guess that only goes for stuff *other people do*, not certain people who "have no time for talk"..

You guys do what you do, but you realize this project is starting to feel less and less a community project and more and more a project controlled by a few people who don't like communicating with the community. And personally, I'm feeling less and less happy about being a part of this as time goes by.

**Comment by denschub** [comment]
In your comment, you are complaining about *"us"* doing stuff in private while also suggesting we should discuss this in private? What the heck man? Is it that time again? Are you seriously complaining about us not sticking to Loomio right after I linked you the proposal where all the decisions were made?

Firstly, let me quote the outcome that **you** have written:

> The diaspora core developers do not want to communicate changes.

So why are you even complaining about this? You think we don't want to communicate, we made a proposal about that and the community said they are fine with us not communicating. Also, if you would be so kind and take the time to read my initial comment, you'll see that we are actually in contact with Friendica.

> I'm feeling less and less happy about being a part of this as time goes by.

Yes, yes, we've been there before, you've said that multiple times. Not too sure what you want to achieve with repeating the same sentence over and over again, but maybe, just maybe, we could start using GitHub discussions as a place to... discuss technical topics? Now that would be nice.

Randomly adding "I'm sooo unhappy with the decisions you have done without me" to any discussions is really a waste of time. There is no decision done here yet. This is an planning issue and Github has this awesome invention called "comments". We're here to discuss stuff. We have discussed stuff in the past. We even had discussions via IRC, for example about #26. I'm really sorry if you feel excluded. Maybe that's because you're only worried about making all the other networks happy without thinking about what our project actually needs to get out of the horrible situation we're in right now. Maybe it's because you always start attacking people when they do stuff you don't like. Maybe it's because you never actually have added anything useful to the whole federation discussion except for unsustainable accusations that we don't care about anything.

Fine. Go ahead and blame us because we're apparently making decisions without involving anyone. No, better, blame only me because @SuperTux88 is doing awesome work. This federation gem already consumed more work time than I'd ever be able to spent on a side project and it really hurts seeing such work getting goofed on. Honestly, that's a shame.

**Comment by jaywink** [comment]
> Are you seriously complaining about us not sticking to Loomio right after I linked you the proposal where all the decisions were made?

There was no decision made - [you threatened to stop working on the federation layer](https://www.loomio.org/d/ohy5c3En/changes-to-the-diaspora-protocol#comment-791666) if the proposal passes and I ended the proposal. You can't call that a "we can do anything" mandate.

> This is an planning issue and Github has this awesome invention called "comments". We're here to discuss stuff.

Yeah, a planning issue which for example I would have never found had it not been for Fla. When planning core breaking changes I would expect the planning to be done in tools we've agreed on, ie Loomio. But apparently that only goes for stuff other people plan. On certain stuff everybody has to follow all the commits because there is no time for communications.

Great that things are working out great and you don't see a problem with how things are going.

**Comment by jaywink** [comment]
Also, yes, I think @SuperTux88 is doing awesome work. I just don't agree on implementing that work is planned. Apparently it is not required to follow normal project guidelines of involving the community when it comes to renewing the federation core.

As project administrator @denschub , you should be enforcing such responsibilities towards the community, not @SuperTux88 .

**Comment by svbergerem** [comment]
@jaywink What is the problem? @SuperTux88 is working on the federation gem in his repo and nothing will change for us as long as we don't update the gem version in the diaspora\* repo. @SuperTux88 didn't even change that much but opened issues for the planned changes so everyone is able to give feedback about the changes.

Everyone who is interested in working on the federation can watch this repo and will be notified about changes. You will be notified about most changes without even reading any commit message. @SuperTux88 has already been talking with @annando about planned changes and the planned changes are documented in these issues. You can also see which changes have been implemented by looking at the checked points. That doesn't mean that they have been released and that especially doesn't mean that they are already used by the diaspora\* code. If anyone has any objections we can still change the stuff.

We talked about this several times and it was pretty clear that the current federation protocol needs to be fixed at some places. @SuperTux88 is working on an implementation of the current protocol and while implementing this he finds stuff that doesn't make much sense and should be changed to improve the federation protocol. These planned changes are documented in these issues and whoever wants to can give feedback.

The changes are planned in 3 phases so everyone has enough time to adopt implementations. The federation gem in version v0.1.0 (which is still unreleased but should be part of our release 0.6.0.0) doesn't add any breaking changes but prepares the federation code so it will be able to receive messages after the breaking changes have been implemented and released.

@Flaburgan wrote
> I just feel a little bit weird about breaking stuff in a minor release. But we will see at this time, maybe we will be ready for 0.7 who knows :)

which is a totally valid point. At this moment there are no breaking changes and we can just use this gem for the 0.6.0.0 release. Then we can see how fast podmins switch to the new version and how fast other social networks in the federation implement the planned changes. Depending on this we can decide when and how we would like to release a diaspora\* version with the first breaking federation changes. This decision will happen in the diaspora\* repo.

Again: what is the problem? I currently don't get it.

**Comment by annando** [comment]
I'm in constant contact with @SuperTux88 according changes in the protocol. When there was a minor glitch in the communication between Diaspora and Friendica we fixed it in one day and had a new release for it in two days.

At Friendica we have a release cycle with 3 or 4 releases per year. It should be no real problem changing that.

It would only be good to have some minimal documentation what we exactly have to change. The signing process is a little problem there - but @SuperTux88 does know about it.

**Comment by denschub** [comment]
@SuperTux88. So, after thinking about it, `diaspora_id` seems rather ambiguous and I feel like we should make clear that's the elements author. What do you think about `author_id`? `sender_id` might also be a possibility but we use the term `author` in the code quite frequently.

**Comment by annando** [comment]
At Friendica we are having the "author" and the "owner". 

For example: The author is the one who wrote the comment. The owner would be the one who relayed the comment.

I would agree to use a word like "author" or "sender" - just to emphasize that it is the id of a person.

**Comment by SuperTux88** [comment]
Yes, `author` sounds good. `author_id` is used in the diaspora-database for the auto-incremented id of the person-entity, so that could be weird. But I think we can simply drop the `_id` in the federation-messages. That would mean:

* `diaspora_id` -> `author`
* `recipient_id` -> `recipient`
* `participant_ids` -> `participants`

I'll change this in the issue text, if nobody has objections.

**Comment by denschub** [comment]
Even better, no objections.

**Comment by jaywink** [comment]
OK, so got of to a bit of a bad start with this. I was linked to this pull request, heard first time (as a core member) about major changes already submitted as code to the federation layer and saw that removal was already planned to be done in a minor release after 0.6. I assumed that the schedules in the PR had already been discussed with the core team as I know @SuperTux88 works closely with Dennis (and Dennis had not commented on these schedules as he is usually pretty quick).

It seems I was wrong. I apologize for the noise and hassle.

@SuperTux88 I think it would be a good idea if in an external repository you don't add any deprecation or removal suggestions to be used by the project, to avoid confusion like this. It's good to plan versions in this library where defaults will change and things will be removed, but this library cannot make assumptions when those versions will be pulled into diaspora core (or any other project using this library).

A few words about (not at all related to this PR) diaspora* release and versioning, as agreed in Loomio votes:

* Semantic versioning used, specifically one part of the API defined as "The federation protocol" -> this automatically means breaking changes to the federation protocol cause a major release. [Proposal](https://www.loomio.org/d/1PXAMDxT/adopt-a-versioning-scheme-and-release-cycle?proposal=aF0k8YqM). Also note 0.x is major, not minor.
* The minor release process defines things like "should not cause troubles for the podmins", "release new versions containing bug fixes only" and so on. I'm pretty sure we all agree removing federation compatibility does not fall in a minor release. [Proposal](https://www.loomio.org/d/mq6HoprD/fixed-schedule-for-bugfix-releases?proposal=sIUmN3eA).

Let's please keep to decisions made or make new ones via the proper channels.

This doesn't mean a 0.7 can't come out within the proposed 8x minor releases. I think instead of agreeing on what major version to push out removing federation parts we should agree on a minimum timeframe and then include this in the next major after that. But again, not in scope of this PR.

Thanks for your work @SuperTux88 . I would appreciate if you remove the diaspora releases from the PR descriptions - just to not confuse anyone, especially random people ending up here and thinking these are set things.

**Comment by denschub** [comment]
> It seems I was wrong. I apologize for the noise and hassle.

This is not the first time that such a story happens. You know that. Please consider thinking and asking (over an appropriate channel...) next time before randomly attacking people. You've already lost all sympathy in your last attack train and this is getting really annoying. Saying "oh, I'm sorry" afterwards is by far not a resolution for bad behavior, especially not in an open source project.

Anyway. I'll draw a fancy line here now:

---

First, I'd not consider this an *external* repository per se since this is likely going to be moved into the diaspora organization once it is fully integrated into the core and after a passed Loomio proposal. Also, after that step, I'll submit a proposal to add @SuperTux88 as a core member since he will obviously be our federation guru then. But that's just an idea. Maybe people don't like him and the proposal fails, who knows.

I have to agree with @jaywink in some parts here, the step 0.1.0 -> 0.2.0 could be done in a minor without hassles, since adding a second, more stable and predictable way of doing things can considered a bugfix. However, removing old stuff cannot be considered a bugfix and thus would not really qualify for minor releases.

**Comment by SuperTux88** [comment]
@jaywink The "release-schedule" was only a proposal ... also "3-4 diaspora minor-releases" doesn't mean, that the release in which the new library is used in diaspora is not a major-release of diaspora. But this is out of scope here. That can be discussed at the PR where new versions of this gem are pushed to diaspora.

Maybe I should have used 4-6 Month instead, but if this is the only thing that bothers you, then you can do this in a nicer way by simply making a better suggestion instead of randomly yelling around and assert that everything is decided yet (which it isn't). But I think it is a good idea to make the time-plan with diaspora-minor-releases, because it is strongly associated with diaspora-releases.

Also 0.x are major-releases of this gem, so this is correct. I didn't wrote the diaspora release numbers of the future-releases, because this is out of scope of this gem. The only release I wrote was 0.6.0.0 because I'm aiming to add this gem to this release (because I need stuff that is only in the develop-branch of diaspora, so this is the earliest release I can add it).

**Comment by SuperTux88** [comment]
@denschub @annando I edited the issue-text and changed the new names.

**Comment by jaywink** [comment]
@SuperTux88 

> Also 0.x are major-releases of this gem, so this is correct.

I meant 0.x is major for diaspora* releases. Our semver defines the first 0 as "extra" to semver. I'd still prefer if you removed the diaspora release schedule from the issue, but your repository..

**Comment by jaywink** [comment]
> I have to agree with @jaywink in some parts here, the step 0.1.0 -> 0.2.0 could be done in a minor without hassles, since adding a second, more stable and predictable way of doing things can considered a bugfix. 

Actually, 0.2.0 of this gem will completely break federation too, due to `send messages with new property names`. If it didn't, it would need to send out two copies. But again, gem 0.1.0 at diaspora 0.6 is something that no one is objecting to - anything else should be planned in the proper places..

**Comment by SuperTux88** [comment]
> I meant 0.x is major for diaspora* releases. Our semver defines the first 0 as "extra" to semver. I'd still prefer if you removed the diaspora release schedule from the issue

I know that you meant diaspora-releases, but I wrote the gem-version numbers in the issue and for the gem they are major-releases. I don't care here, if the release where it will be added to diaspora is a minor or major (I think major is better, but this discussion doesn't belong here).

I didn't write any diaspora-version numbers except 0.6.0.0. Do you want me to remove the 0.6.0.0? Or do you mean the time-span between two releases? As already said: this gem is strongly associated with diaspora-releases (because it doesn't make sense to release a new gem-version without adding it to a diaspora release), so I think it makes sense to use diaspora-minor-releases as time-span?

**Comment by SuperTux88** [comment]
I added `status_message`: `raw_message` -> `text` to this issue, because currently we have this:
* `comment`: `text`
* `message`: `text`
* `photo`: `text` (currently not actively used by diaspora)
* `status_message`: `raw_message`

And I think we should use `text` everywhere 😃
