### ISSUE TITLE
Entity fetching

### ISSUE THREAD

**Issue by SuperTux88** [diaspora/diaspora_federation#31]
After the diaspora security release 0.5.7.1 I created a new way to safely fetch entities:
- fetched entities are now signed with the magic-envelope (see #30, same format as for public messages)
- only public entities are available for fetching. (same as before)
- new fetch path: /fetch/:type/:guid
  - `type` is the entity type in snake_case, the first version supports `status_message`, `reshare` and `post` (`post` includes `status_message` and `reshare`)
  - `guid` is the guid of the entity to fetch
- if a pod isn't the owner of the entity it should redirect to the correct pod (it can't sign the magic env anyway)
### Example:

We receive a comment with author alice@pod-a.org and we don't know the parent of this comment. We should call `https://pod-a.org/fetch/post/<parent_guid>`.
- If the missing post is also from alice@pod-a.org (or any other user on pod-a.org), we get the magic envelope with the post, signed by the author of the post.
- If the missing post is from bob@pod-b.org, pod-a.org sends us a redirect to `https://pod-b.org/fetch/post/<parent_guid>` and we can fetch the magic envelope from this url.
- If the post is not public, we should receive a 404.

**Comment by cmrd-senya** [comment]
Cool stuff. I was going to open an issue about standartizing the fetch feature, because it relied on internal API, which is bad, and then I noticed your commits, so I didn't post the issue, because it solves it :)

This will help to make diaspora* <-> Friendica integration better, because Friendica now doesn't fetch old posts of a diaspora* user, when it first discovers him.

However, you don't describe a way here to fetch public posts for a specific user. Is it possible or in plans?

**Comment by SuperTux88** [comment]
Fetch the first 15 public posts of a user after first discover him isn't a good solution anyway because it doesn't even really work within diaspora. I think we need another solution for this problem. (maybe link to the profile of this user on his pod, because this always shows all public posts)

**Comment by cmrd-senya** [comment]
> maybe link to the profile of this user on his pod, because this always shows all public posts
This way it wouldn't be possible to comment user's post on this page.

Maybe we could make the fetch query every time someone requests the profile page? And use HTTP Cache-Control to indicate there is no updates to save traffic between pods - reply with 304 status when new post were added since the last query.

**Comment by SuperTux88** [comment]
It isn't possible to comment the post now, if it was written after the first discovery. And fetch every time you visit the profile page isn't a solution either. Because make a http call is slow and create load (even with 304). Also this wouldn't help, if the post you want to comment is not in the first 15 posts.

I still think that link to the users profile is better, because you see everything then. And we should add a possibility to fetch a specific post (which can be done with the fetch routes described in this issue), similar to what friendica has, to start sharing with someone from their profile page.

**Comment by cmrd-senya** [comment]
How does the foreign pod would know your identity on your pod? So you could set up sharing and, possibly, comment.

**Comment by SuperTux88** [comment]
you need to tell him your identity, the same as if you start sharing with someone from his profile-page on another pod (currently only available from friendica profiles, but works also with diaspora)

**Comment by cmrd-senya** [comment]
Do you mean like linking the remote profile as ```https://domain.tld/people/:guid?from=someone@anotherpod.tld```?

**Comment by SuperTux88** [comment]
yes, if you can add your identity as a parameter. But I think this should also work without the parameter, when you visit a profile or a single-post-view linked somewhere else. Then you can ask the user for his diaspora-id.

**Comment by cmrd-senya** [comment]
So if we open a profile page on another pod, to comment we must click some "Comment" link, which will redirect us to a single view of the post on our pod, right?

And what about likes? For me it is a usual pattern to scroll someones profile page and give likes to some posts. I think many people do that. And like feature is something that must work without a required redirect to a different place. I think, it would be a huge loss in usability.

It's not hard to determine if we need to pull posts - it is necessary only when there is nobody with whom a remote person shares. So in case when we have the sharing set up we may leave everything as is.

In the case when we need to fetch post, we may do something different.

What if we do the following:
1) Open a profile of the remote person on our pod and load known posts for the person.
2) Then javascript on the pages loads ```https://remotepod.tld/people/:guid.json``` and adds the absent posts to the stream.
3) If user comments or likes the posts that were absent in the stream, then the respective controller will call your fetch node on another pod to fetch the required post.

It may work a little bit slower than what you proposed, but optimizations, Cache-Control and background loading of the post will make in smoother while greatly improving usabilty by not forcing a user to reload a page for like/comment.

**Comment by SuperTux88** [comment]
I thought about `https://remotepod.tld/people/:guid.json` already, but this wouldn't work with friendica/redmatrix/hubzilla/whatever. But if we make the `/fetch/:type/:guid` path part of the protocol, it would work with every software.

And it **IS** hard to determine if we need to pull posts. You don't know if there are posts missing in the persons profile-stream. Maybe you are now sharing with this person, but your pod doesn't know old posts, or maybe there are some missing in the middle? The only stream that is complete is the stream on the pod of the person.

**Comment by cmrd-senya** [comment]
Ok, then we could add a path like ```/fetch/person/stream/:range``` and load it from the javascript of the local pod's profile page. Thus we'll get the post stream from the remote person's pod while having a possibility to like and comment it locally smoothly, without the page reload.

**Comment by denschub** [comment]
No, we cannot. First of all, we'll get into troubles with the Same-Origin-Policy and I see no reason to add a CORS header to fetch resources. Also we really do not want to force the users client to connect to anywhere else than the users pod for privacy reasons.

**Comment by cmrd-senya** [comment]
> Also we really do not want to force the users client to connect to anywhere else than the users pod for privacy reasons.

Then we can't link to a profile on the remote pod as a remote link for the same reason.

**Comment by denschub** [comment]
There is a huge reason between fetching resources automatically and linking to an external site.

**Comment by cmrd-senya** [comment]
Hmm, if we fetch resources we don't need to tell external site that the user alice views your profile. If we link to an external website, we'll have to tell it alice's diaspora-id since we want to have a redirect back in order to comment, etc. Otherwise we'll have to drop the possibility to comment or like posts on the profile page, which is huge usability loss. So linking to external site is worse in terms of privacy.

**Comment by denschub** [comment]
What do you want to achieve here? First of all, the URLs for posting/liking/whatever is the same for all users on the pod, so there is no reason to submit the username. Next, you already suggested to submit your identity some comments above anyway, so you are a bit contradicting yourself. 

We already agreed that we do not really know on when to fetch the posts, except if there is no copy of the profile on the pod, which will trigger a fetch anyway. As soon as the profile is on the pod, we do now know if the user simply hasn't posted anything visible to us or if posts are missing because of federation issues. That means, by implementing your suggestion, we would need to fetch posts on all profiles all the time. Nah.

Also, this is the federation gem, isn't it? We need a reliable of fetching posts inside the federation library in case we receive a interaction on a post we do not already have received yet. We could even trigger a asynchronous loading of posts under certain circumstances on the backend like we do for discovering new user profiles in the search for example. In any case, that's something that has to be considered on the implementation side (that is, in diasporas core) and not here.

Since I feel we have rather different views of UX/UI and privacy, that is something we should discuss on Loomio so others have the chance to comment as well. Otherwiese, people will start complaining about *the evil core* doing decisions in *hidden repositories* again, eh? :)

**Comment by cmrd-senya** [comment]
>Since I feel we have rather different views of UX/UI and privacy, that is something we should discuss on Loomio so others have the chance to comment as well.

Sure.

But this issue is about entity fetching, and I think the feature should allow to fetch all posts of the user (or some limited ranged portions), and not only posts one-by-one. That question is in scope of the issue. However, it depends on the UX/UI decisions, so maybe be it must be left before any loomio discussions are conducted.

**Comment by SuperTux88** [comment]
This issue is about fetching (public) entities (with a guid) that are also federated. It is here to add a simple and flexible way to fetch such entities even for future entities. Which types are supported is part of the software that implements the callback (in our case diaspora, as described this would be `post`, `status_message` and `reshare` for the beginning).

As long as we don't federate streams, this has nothing to do with this issue.

**Comment by Flaburgan** [comment]
I have tons of errors like this one in my logs:
```
[2016-11-17T07:02:34] INFO  PID-23082 TID-6767620239660 Rails: Started GET "/fetch/post/9b39ca308e8c0134c1a6782bcb452bd5" for X.X.X.X at 2016-11-17 07:02:34 +0100
[2016-11-17T07:02:34] INFO  PID-23082 TID-6767620239660 ActionController::Base: Processing by DiasporaFederation::FetchController#fetch as */*
[2016-11-17T07:02:34] INFO  PID-23082 TID-6767620239660 ActionController::Base:   Parameters: {"type"=>"post", "guid"=>"9b39ca308e8c0134c1a6782bcb452bd5"}
[2016-11-17T07:02:34] INFO  PID-23082 TID-6767620239660 ActionController::Base: Completed 500 Internal Server Error in 5ms (ActiveRecord: 1.1ms)
[2016-11-17T07:02:34] FATAL PID-23082 TID-6767620239660 Rails: 
DiasporaFederation::Entity::ValidationError (Failed validation for properties: property: root_author, value: nil, rule: not_empty, with params: {}):
  lib/diaspora/federation/entities.rb:191:in `new'
  lib/diaspora/federation/entities.rb:191:in `reshare'
  lib/diaspora/federation/entities.rb:24:in `post'
  config/initializers/diaspora_federation.rb:112:in `block (3 levels) in <top (required)>'
  lib/rack/internet_explorer_version.rb:34:in `call'
```
When I go to `/post/9b39ca308e8c0134c1a6782bcb452bd5` I have a 404 so I guess this means the post has been deleted. Is that something you're aware of?

**Comment by SuperTux88** [comment]
It is [/posts/9b39ca308e8c0134c1a6782bcb452bd5](https://diaspora-fr.org/posts/9b39ca308e8c0134c1a6782bcb452bd5) (/posts/ not /post/), and it is a reshare where the root post was deleted.

A reshare without a root is invalid for the federation, so it should probably be handled in diaspora, so it doesn't try to create a federation-entity without a parent. The federation-library would then return 404 instead of 500, which is better.
