### ISSUE TITLE
new entity for "start sharing with"

### ISSUE THREAD

**Issue by SuperTux88** [diaspora/diaspora_federation#32]
I discussed this with @annando a few days ago. The main reason was, that the "stop sharing with you" currently is a `retraction` with the type `Person` which is weird, because the retraction should always be the same type as the original message. And we thought that `Request` is a weird name anyway for "start sharing with" and friendica has `following` and `sharing`.
### new `Contact` entity

I created a new entity for this with a better name for this action. The xml that diaspora would send look like this:

```
<contact>
  <author>alice@example.com</author>
  <recipient>bob@example.org</recipient>
  <following>true</following>
  <sharing>true</sharing>
</contact>
```

Diaspora doesn't support `following` and `sharing` yet, so both would be true now, but this change sometime: https://discourse.diasporafoundation.org/t/sharing-vs-following/524

If someone stops sharing/following, he sends the same message with false for `following`/`sharing`.
### v0.1.0 (for diaspora 0.6.0.0)
- [x] send the old Request entity
- [x] send the old retraction with type `Person`
- [x] can receive and parse old Request entity
- [x] can receive and parse new Contact entity
- [x] can receive and parse old retraction with type `Person`
### v0.2.0 (for diaspora 0.7.0.0)
- [x] send the new Contact entity for start and stop sharing
### v0.3.0 (probably for diaspora 0.8.0.0)
- [ ] remove old Request entity and cleanup.

**Comment by annando** [comment]
Do you think "author" is necessary? This is a message type that surely isn't relayed. So we have the author already through the salmon part.

To clear the direction of "following" and "sharing" in this context:
* "following": "author" wants to read the content of "recipient"
* "sharing": "author" wants to send content to "recipient"

Correct?

BTW: We don't need the retraction here. We simply could set one or both of these values to "false" to signalise the "unsharing" or "unfollowing". A simple retraction without specifying the direction would be too unspecified.

**Comment by SuperTux88** [comment]
I think we should have the `author` as we have it for all other entities too.

following/sharing: correct.

I think a retraction is better, because it is more what also happens in the database. If someone switches from `following` to `both`, we send an updated `contact` entity and update the state in the database. But if someone disconnects completely we send a `retraction` and delete the contact in the database.

**Comment by redmatrix** [comment]
The question then remains what is different about what happens if you set one or both to false without sending a retraction. Hubzilla uses this kind of permissions construct. Granular permissions can be added/removed and the act of adding anything initiates a connection, and there is also a separate "remove the connection record" message matching your retraction. I'm just trying to clarify if removing all permissions would be allowed.

**Comment by SuperTux88** [comment]
and what should be the difference between delete the contact and remove following and sharing?

I can handle this, that both false also deletes the contact, but I think the more logic way would be with the retraction.

**Comment by annando** [comment]
I think only a retraction should delete the contact. Sending "false/false" would simply remove the permission but the contact would be kept on the receiver side.

**Comment by SuperTux88** [comment]
yes, I think that would be the expected behavior (delete with false/false would need a special handling), but what should be the behavior for the user on the frontend, if he has a contact with false/false? Diaspora would never send a false/false.

**Comment by annando** [comment]
I think this has to be defined, once that Diaspora can handle following/share. Friendica currently doesn't know that state as well. Of course we could define that this isn't allowed at the moment.

**Comment by SuperTux88** [comment]
@redmatrix can you say what should happen if we have a contact with false/false?

**Comment by redmatrix** [comment]
In our model record deletion is usually reserved for a channel committing suicide so that we don't leave orphans. Otherwise a connection can be one-sided and doesn't imply you can do anything at all. "Unfriending" doesn't actually remove the record on the other side of the fence. It just reduces or removes permissions. It's the only model that makes sense for us because we have a lot more permissions beyond basic stream access; controlling everything from photo upload ability to chat and remote administration.

**Comment by SuperTux88** [comment]
@redmatrix so redmatrix sends a false/false instead of a retraction?

`account_deletion` has its own message and includes delete all orphans (so we don't need to send thousands of retractions).

**Comment by redmatrix** [comment]
> so redmatrix sends a false/false instead of a retraction?

Essentially yes. We can emulate whatever model you use, so I'm mostly just trying to clarify your model behaviour. If one can send a message with true/true I'd like to know if sending a message with false/false is prohibited or if I should trap that case on our side and send a retraction instead of our normal permissions change.

**Comment by annando** [comment]
BTW: I'm not sure if we should accept the combination "following=false, sharing=true" if the previous value wasn't "true, true". This would mean: "I don't want to read your stuff and you don't know me - but I want you to read me". This sounds a little bit like: "I want to spam around" to me.

**Comment by SuperTux88** [comment]
"following=false, sharing=true" would mean: "I want that you can see my profile and send me private messages, but I don't follow your posts, because you spam"

**Comment by SuperTux88** [comment]
After implementing this, I came to the point, that it would be better to use a false/false `Contact` (as suggested by @redmatrix) instead of a `Retraction`. Because:
* a `Contact` with false/false contains the recipient in the signed part of the message, which makes the message unique.
* a `Contact` doesn't have a `guid`, so when sending a `Retraction` you would need to use the guid of the Person, which is confusing and dirty.

I'll update the issue-description.

**Comment by annando** [comment]
What should the receiver do when it received the false/false message? And I guess it would be great to have some small table with the different values (true/true, true/false, false/true, false/false) and what to do with these values. This table should include the previous state, means: "If the previous state was true/true and is now false/true, then ..."

**Comment by SuperTux88** [comment]
What he does is the receivers (software) decision, this is only a status-update. If you delete the contact or only update the state in the DB depends on the database-layout of the receiving software. Diaspora would update the entity in the database and delete it, if there is also is no outgoing connection.

Also it does not depend on what the previous state was.

**Comment by jaywink** [comment]
Are both `sharing` and `following` a must in the XML? In my world I've always had these separated and have just created two objects on receiving something from Diaspora (since it's currently `true/true`). Now the difficult part is converting a `following` or `sharing` to one unified object. I can write custom code to handle that but no one likes custom code, so hence the question - can I leave one or the other out?

**Comment by SuperTux88** [comment]
They are optional, if they are missing, they are `true` by default. Diaspora can currently only handle `sharing` and ignores the state of the `following` flag (because we can't currently display that to the user and it isn't in our database schema neither), but diaspora sends the `following` flag as `true` together with `sharing`, because that's what happens when someone starts sharing with somebody (on diaspora), it's also following.

**Comment by SuperTux88** [comment]
Oh, I was wrong, they aren't optional, as by the specs here: https://diaspora.github.io/diaspora_federation/entities/contact.html 

Diaspora handles them as `true` by default, but I have no idea what Friendica does. If Friendica also handles them as default `true`, we can maybe change them to optional? cc @annando for Friendica

**Comment by jaywink** [comment]
I'm not sure it matters what the defaults are. If software assumes any defaults basically you always have to send both - otherwise the default could override something that was sent before. The only real way to separate them would be to send them in separate objects. As long as they're in the same payload, receiving software could default the values either way.

Thanks for the confirmation, will just write some extra code to collect both in the same payload 👍
