### ISSUE TITLE
Stop accepting updates from specific user (blacklist)

### ISSUE THREAD

**Issue by Zauberstuhl** [diaspora/diaspora_federation#40]
* Is this something we want (closing accounts in respect of non-local users is not possible)?
* should it be handled in the federation gem?

I played with it here https://github.com/sechat/sechat/commit/c7292958c2000d35e8dbcb5b67a44a1268d1cbe8

**Comment by SuperTux88** [comment]
I think blacklisting should be handled in diaspora itself and not in the gem, because it is nothing protocol specific and depends on how the applications that uses the gem handles blacklisting.

But you shouldn't parse the XML twice. If you want to blacklist the user completely (send and receive), you can add your blacklisting here: https://github.com/diaspora/diaspora/blob/fddec628287c8b0477faa9e89aff6401cde11461/config/initializers/diaspora_federation.rb#L74-L77

But I think we should still receive `account_deletion`s and `retraction`s from the blacklisted user, so I think that https://github.com/diaspora/diaspora/blob/develop/lib/diaspora/federation/receive.rb is a better place. And maybe you also don't want to block the reject logic, if the parent author of a post ignores the blacklisted user.

Also blacklisting should be stored in the database and not in the diaspora.yml.

**Comment by Zauberstuhl** [comment]
awesome thanks for the input I will think about it
