### ISSUE TITLE
federation relay issue

### ISSUE THREAD

**Issue by zotlabs** [diaspora/diaspora_federation#68]
I'm trying to track a weird federation issue which is likely a bug on my end but it's being manifested inside Diaspora - so I need some assistance. Here's the scenario:

Three Actors:
D0 - on Diaspora (wk3.org in case there's a versioning issue present) using the "transition" protocol (receives old+new, sends old)  
D1 - on red, using the new protocol for send, receives either
D2 - on red, using the new protocol for send, receives either

D0 sends a limited post which is received by D1 and D2. All is well.
D1 comments.
D0 receives the comment and it is displayed in the D0 stream.
! D2 does not receive the comment.
D2 comments.
D0 receives the comment and it is displayed in the D0 stream.
! D1 does not receive the comment.
D0 comments.
D1 and D2 receive the comment and it is displayed in their stream

Investigating the logs on red, the comments sent from red were accepted for delivery (2xx response) by Diaspora and as the comments were then displayed in the Diaspora stream it is presumed that the author_signature and salmon validated and that decryption was successful.

In the logs I see no inbound traffic from Diaspora from the comments that were relayed from red. So it appears that outbound delivery was not attempted or a failure/protocol violation prevented the outbound (downstream) delivery. As the comments were received and displayed on Diaspora it is unclear what kind of protocol violation would only affect downstream delivery and not result in a rejection of the incoming comments.

Any assistance or pointers would be appreciated.  Here is a protocol log of one outbound comment prior to magic-sig and encryption encapsulation:

````
<?xml version="1.0" encoding="UTF-8"?>
<comment><guid>e507ece71c03111d93944184c18e18f582b4dc88a5f5e05d79e02f7030f1a05d@hz.macgirvin.com</guid>
<parent_guid>8fa50c703f5c01351a021acf4c22f836</parent_guid>
<text>test reply2</text>
<author>d2@hz.macgirvin.com</author>
<created_at>2017-06-30T00:57:34Z</created_at>
<author_signature>CHzNGHtwJEwNCnTFqdF/fjTQA5UKYCqS3Jewib1Q+IrTZFLNoKCy+SEjFNdsLoXm8EI/nxATAPovPo0ru8sHjWwdqqrAKcJy9CSj0E91uAiSel4RsQQBvKtQB8JnZqQTII8tgs6V9vnxS0JZYkXylY9Gl+eu9nbuRpFZuzzSoJhzXe3CTFR5CVas0kIlG7Nol0MWK7vFCE7iAKyEbqteTGyCPRPtZKFqnbBEyz7+vTRdwouwk4vXSbEG53URQQoBQ9Q6m6oalVC5ZgL30Zm70SbHvz/xK2qgVhlrpAkOsNkbALx7HuJIkIgk6WtnNQz5HbxPfFdjW0jR0pwz9EditH9KDaHzGGe4QFGEki8nAPoPiOJ0eg8gpQJ7CXD7KUDj4u4t6CGM7BDUjulpK+sS90ATFZSH63YqaavgFi6YdaXU9snnS2cEy4mLV77M8tppim8Vz56OS+SfmIt5xUILkA1pe9FSUH9GVUYM1JgV6d3X94mlbrRPpisfDeKPnI/2n9ryljxL6UQxAu+gALMiB1BlRbKYja1027NTD7CsojCBvoZP4WAUXPATKdIopH0i/OfcCu1N55loqmqGSt7VAwqKoQPEgrbrJ+iKhHoOhej1xQ7ma02teVL9CQPG1tV7VgDOgfTsoCdOAXWPWsc/sdwkuqfRbx4711QpBu9Q5uU=</author_signature>
</comment>
````

**Comment by SuperTux88** [comment]
Hmm, I have no idea what fails, since receive from D0 seems successful it should also be relayed.

Can you test the same with D0 being on nerdpol.ch and then tell me the guid of the failed comment? That way I would have access to the logs and can see if there is an attempt of sending it out again.

**Comment by SuperTux88** [comment]
Oh, just to be sure: D1 and D2 are on different servers? Because if they are on the same server, diaspora doesn't send it back to the server from which it was received, because we know that server already has the comment (the visibility is only on the post, so everybody who can see the post can also see all comments). When sending comments (D0 comments), we send it to all users on a server, because it could be something wrong with D1 (closed account, but we didn't receive that info), so for the case D1 can't receive it correctly, D2 can receive it and then D2 can still see the comment. If D1 already received the comment, the message to D2 can be ignored.

**Comment by zotlabs** [comment]
That appears to be the situation. So basically we need to create a tunnel around the post author's privacy expectations without introducing any privacy issues/violations. We actually cannot do that. The ability to comment is a specific permission and comments can be filtered or blocked by the owner. A downstream contributor cannot make these kinds of decisions without involving the post owner.

**Comment by zotlabs** [comment]
Ah, but by definition the owner in this case is going to be on Diaspora and have a known set of permissions. As long as I document the tunnel and its limitations for future travellers we can probably live with that. If you folks ever support forums or any permissions beyond 'friend/follower' or allow connection filters you may need to rethink how you do this. Closing.

**Comment by SuperTux88** [comment]
> comments can be filtered or blocked by the owner.

Diaspora sends a `retraction` back to then sender when the comment is blocked. So for now diaspora assumes that everybody on the same server as the sender of the comment already has the comment.

But I already thought about changing that, and send the comment also back to the sender. That would allow to display the comment only to the author and then unlock for all when approved from the post author. But diaspora doesn't need that, so it would only end in many messages being ignored (because the comment is already there, that's why I didn't change that yet). But if that helps you, I can change that in the 0.7.0.0 diaspora release. That wouldn't help you with currently existing servers, so you still need a workaround for that, but you can remove it later again.

What do you think, should we change that and send comments also back to the sender-server?

**Comment by zotlabs** [comment]
Would prefer to have the comments relayed to everybody; but unless side channel delivery is disabled on Diaspora it's somewhat irrelevant.

Even if there is no privacy violation on your side, the side-channel delivery on the Diaspora side can cause a privacy/policy violation on our service. If D1 and D2 were on Diaspora and D1 was blocked or filtered by D0 (on a zot enabled platform), the comment would still flow to D2 which was not the owner's intention. We can't stop this currently and I'm assuming that enabling downstream delivery to all doesn't mean you would disable the side channel delivery on Diaspora. We just have to document this amongst the list of things that don't work correctly if you enable external federation protocols.

**Comment by SuperTux88** [comment]
That was a problem on diaspora for a long time, that's why we started sending a `retraction` back to the sender when a relayable was blocked at the parent author. That was the easiest and fastest solution, because it was possible without a protocol change and already supported by all pods.

But we should probably start sending relayables back to the author, so we can work on that later.

@annando how does friendica handle relayables (when the parent author is on friendica)? Does it send them back to the author and other people on the authors server? Or does it handle them the same way as diaspora currently does it (only send them to other servers)?

**Comment by annando** [comment]
Friendica treats users on the same server mostly like users on a different server.
